import type { TechNode } from 'shared/game-types'

export const TECH_TREE: TechNode[] = [
  // Tier 1
  {
    id: 'basic_infrastructure',
    name: '基础设施',
    description: '掌握城市基础设施建设技术，解锁消防局',
    tier: 1,
    rpCost: 30,
    effects: [{ type: 'unlock_building', target: 'fire_station' }],
    prerequisites: [],
  },
  {
    id: 'basic_education',
    name: '基础教育',
    description: '建立教育体系，解锁学校',
    tier: 1,
    rpCost: 40,
    effects: [{ type: 'unlock_building', target: 'school' }],
    prerequisites: [],
  },
  {
    id: 'urban_planning',
    name: '城市规划',
    description: '掌握城市规划技术，解锁公园',
    tier: 1,
    rpCost: 35,
    effects: [{ type: 'unlock_building', target: 'park' }],
    prerequisites: [],
  },
  // Tier 2
  {
    id: 'law_enforcement',
    name: '治安体系',
    description: '建立执法体系，解锁警察局',
    tier: 2,
    rpCost: 70,
    effects: [{ type: 'unlock_building', target: 'police_station' }],
    prerequisites: ['basic_infrastructure'],
  },
  {
    id: 'public_health',
    name: '公共卫生',
    description: '发展医疗体系，解锁医院',
    tier: 2,
    rpCost: 80,
    effects: [{ type: 'unlock_building', target: 'hospital' }],
    prerequisites: ['basic_education'],
  },
  {
    id: 'commercial_theory',
    name: '商业理论',
    description: '商业收入永久 +10%',
    tier: 2,
    rpCost: 60,
    effects: [
      { type: 'permanent_multiplier', target: 'commercial_income', value: 1.1 },
    ],
    prerequisites: ['urban_planning'],
  },
  {
    id: 'power_grid',
    name: '电力网络',
    description: '掌握电力技术，解锁发电厂',
    tier: 2,
    rpCost: 100,
    effects: [{ type: 'unlock_building', target: 'power_plant' }],
    prerequisites: ['basic_infrastructure'],
  },
  // Tier 3
  {
    id: 'advanced_manufacturing',
    name: '先进制造',
    description: '工业效率永久 +15%',
    tier: 3,
    rpCost: 150,
    effects: [
      {
        type: 'permanent_multiplier',
        target: 'industrial_efficiency',
        value: 1.15,
      },
    ],
    prerequisites: ['law_enforcement', 'power_grid'],
  },
  {
    id: 'education_reform',
    name: '教育改革',
    description: '研究速度永久 +30%',
    tier: 3,
    rpCost: 120,
    effects: [{ type: 'research_multiplier', value: 1.3 }],
    prerequisites: ['public_health'],
  },
  {
    id: 'green_tech',
    name: '绿色科技',
    description: '减少工业污染协同半径 -1',
    tier: 3,
    rpCost: 130,
    effects: [
      {
        type: 'increase_synergy_radius',
        target: 'industrial_pollution',
        value: -1,
      },
    ],
    prerequisites: ['commercial_theory'],
  },
  // Tier 4 - Specializations
  {
    id: 'industrial_mastery',
    name: '工业大师',
    description: '解锁工业之都特色路线',
    tier: 4,
    rpCost: 250,
    effects: [{ type: 'unlock_specialization', target: 'industrial_capital' }],
    prerequisites: ['advanced_manufacturing'],
  },
  {
    id: 'commercial_empire',
    name: '商业帝国',
    description: '解锁商业之都特色路线',
    tier: 4,
    rpCost: 250,
    effects: [{ type: 'unlock_specialization', target: 'commercial_capital' }],
    prerequisites: ['commercial_theory', 'education_reform'],
  },
  {
    id: 'utopia',
    name: '乌托邦',
    description: '解锁宜居天堂特色路线',
    tier: 4,
    rpCost: 250,
    effects: [{ type: 'unlock_specialization', target: 'utopia' }],
    prerequisites: ['green_tech', 'education_reform'],
  },
  {
    id: 'balanced_development',
    name: '均衡发展',
    description: '解锁均衡城市特色路线',
    tier: 4,
    rpCost: 200,
    effects: [{ type: 'unlock_specialization', target: 'balanced' }],
    prerequisites: ['advanced_manufacturing', 'education_reform'],
  },
]
